# Generated by Django 4.1 on 2022-08-04 13:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('number_of_reservations', models.IntegerField()),
                ('website', models.URLField()),
                ('date_founded', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_of_stay', models.IntegerField()),
                ('signing_in_on', models.DateField()),
                ('signing_out_on', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5000000)])),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='funct_api.hotel')),
                ('res_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_for', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
