# Generated by Django 4.1 on 2022-11-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funct_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='reservation/'),
        ),
    ]
